---
title: Problem Set 6
author: Tate Mason
format: pdf
---
# Question 1

```{r}
library(Matrix)
library(dplyr)
library(tidyr)
library(magrittr)

df <- read.csv('metrics.csv')
```

## Part A

```{r}
# Creating Variables
id <- df$id
year <- df$year

n <- length(unique(id))
t <- length(unique(year))
nt <- n*t

df %<>% mutate(D=1*(first.displaced <= year & first.displaced !=0), yearf = factor(year))

Y <- Matrix(df$learn)
X <- model.matrix(~ yearf + D-1, data = df)
X <- Matrix(X)

I <- diag(nt)
D <- bdiag(replicate(n,Matrix(rep(1,t)),simplify=FALSE))
M <- I - D%*%solve(t(D)%*%D)%*%t(D)
alpha_hat <- solve(t(X)%*%M%*%X)%*%t(X)%*%M%*%Y
e_hat <- Y - X%*%alpha_hat
var_error = as.numeric(t(e_hat) %*% e_hat) / (nt - ncol(X))
var_alpha = var_error * solve(t(X) %*% M %*% X)
se_alpha = sqrt(diag(var_alpha))
```

```{r}
cat("Part A: Report of Estimates\n")
alpha_hat
se_alpha
```

## Part B

```{r}
calc_group_time_att <- function(df, group, time) {

  if (time < group) {
    return(NA)
  }
  treat <- subset(df, first.displaced == group)
  control <- subset(df, first.displaced == 0)

  pre_period <- group - 2

  treat_pre <- subset(treat, year == pre_period)$learn
  treat_post <- subset(treat, year == time)$learn
  treat_diff <- mean(treat_post) - mean(treat_pre)

  control_pre <- subset(control, year == pre_period)$learn
  control_post <- subset(control, year == time)$learn
  control_diff <- mean(control_post) - mean(control_pre)

  att <- treat_diff - control_diff
  return(att)
}

groups <- c(2001, 2003, 2005, 2007, 2009, 2011, 2013)
years <- unique(df$year)

att_results <- matrix(NA, nrow = length(groups), ncol = length(years))
rownames(att_results) <- paste0("Group_", groups)
colnames(att_results) <- paste0("Year_", years)

for (i in 1:length(groups)) {
  for (j in 1:length(years)) {
    att_results[i, j] <- calc_group_time_att(df, groups[i], years[j])
  }
}

cat("Part B: Report of ATT Estimates\n")
print(att_results)
cat("\n")
```

