---
title: "Problem Set 3"
author: "Tate Mason"
date: Sys.Date()
format: pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(lubridate)
library(broom)
library(stargazer)
library(ggplot2)
library(modelsummary)
library(psych)
library(here)
```

# Question 1

```{r question1.1}
main_data <- read_csv(here("Y2S1/IO/PS3/Data/prod_level_data.csv"))

main_long <- main_data %>%
  pivot_longer(
    cols = c(x1:x4, p1:p4, s1:s4, ave_dist1:ave_dist4, mc1:mc4),
    names_to = c(".value", "time"),
    names_pattern = "([a-z]+)([0-9])"
  )

glimpse(main_long)

main_flipped <- main_long %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "variable")
glimpse(main_flipped)

describe(main_flipped)
```

```{r question1.2}


share_by_rating <- main_flipped %>%
  group_by("x") %>%
  mutate(
    s = "s"
  )

# Scatter plot of market share by Yelp rating with trend line
ggplot(share_by_rating, aes(x = "x", y = s)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(title = "Market Share by Yelp Rating",
       x = "Yelp Rating",
       y = "Total Market Share") +
  theme_minimal()

```
